# Generated by Django 2.2.12 on 2022-11-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='user',
        ),
    ]
