# Generated by Django 2.2.12 on 2022-11-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20221105_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.TextField(),
        ),
    ]
