# Generated by Django 2.2.12 on 2022-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
